//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 百邦所得税汇算底稿工具.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("百邦所得税汇算底稿工具.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon assignment {
            get {
                object obj = ResourceManager.GetObject("assignment", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon border {
            get {
                object obj = ResourceManager.GetObject("border", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Calculator_100px {
            get {
                object obj = ResourceManager.GetObject("Calculator_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Chat_100px {
            get {
                object obj = ResourceManager.GetObject("Chat_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon cloud {
            get {
                object obj = ResourceManager.GetObject("cloud", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Contacts_100px {
            get {
                object obj = ResourceManager.GetObject("Contacts_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon content {
            get {
                object obj = ResourceManager.GetObject("content", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Details_100px {
            get {
                object obj = ResourceManager.GetObject("Details_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap External_Link_100px {
            get {
                object obj = ResourceManager.GetObject("External_Link_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap File_100px {
            get {
                object obj = ResourceManager.GetObject("File_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon flip {
            get {
                object obj = ResourceManager.GetObject("flip", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_assignment_ind_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_assignment_ind_black_48dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_border_color_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_border_color_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_cloud_upload_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_cloud_upload_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_content_copy_black_24dp {
            get {
                object obj = ResourceManager.GetObject("ic_content_copy_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_file_upload_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_file_upload_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_flip_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_flip_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_info_outline_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_info_outline_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_insert_chart_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_insert_chart_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_launch_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_launch_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_list_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_list_black_48dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_local_cafe_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_local_cafe_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_local_print_shop_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_local_print_shop_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_question_answer_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_question_answer_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_receipt_black_24dp {
            get {
                object obj = ResourceManager.GetObject("ic_receipt_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_search_black_24dp {
            get {
                object obj = ResourceManager.GetObject("ic_search_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_settings_applications_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_settings_applications_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ic_vpn_key_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_vpn_key_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Info_100px {
            get {
                object obj = ResourceManager.GetObject("Info_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon info_outline {
            get {
                object obj = ResourceManager.GetObject("info_outline", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon insert_chart {
            get {
                object obj = ResourceManager.GetObject("insert_chart", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Key_100px {
            get {
                object obj = ResourceManager.GetObject("Key_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Knowledge_Sharing_100px_1 {
            get {
                object obj = ResourceManager.GetObject("Knowledge_Sharing_100px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon launch {
            get {
                object obj = ResourceManager.GetObject("launch", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon list {
            get {
                object obj = ResourceManager.GetObject("list", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap LOGO {
            get {
                object obj = ResourceManager.GetObject("LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ms_excel {
            get {
                object obj = ResourceManager.GetObject("ms_excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Numbered_List_100px {
            get {
                object obj = ResourceManager.GetObject("Numbered_List_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap pdf {
            get {
                object obj = ResourceManager.GetObject("pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Poster_100px {
            get {
                object obj = ResourceManager.GetObject("Poster_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Print_100px {
            get {
                object obj = ResourceManager.GetObject("Print_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon QQ {
            get {
                object obj = ResourceManager.GetObject("QQ", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon question_answe {
            get {
                object obj = ResourceManager.GetObject("question_answe", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Quill_With_Ink_100px {
            get {
                object obj = ResourceManager.GetObject("Quill_With_Ink_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon receipt {
            get {
                object obj = ResourceManager.GetObject("receipt", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Search_100px {
            get {
                object obj = ResourceManager.GetObject("Search_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Settings_100px {
            get {
                object obj = ResourceManager.GetObject("Settings_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 档案封面||档案索引||签发单||三级复核||业务约定||当局声明||计划||内控||审核问卷||重大问题||交换意见||资料清单||审核标识||地税、基本情况||基本情况||资产负债||利润||余额表||盘点表||检查表||待办事项||主页||通用记录||税审收费标准||使用说明 的本地化字符串。
        /// </summary>
        public static string Tag1 {
            get {
                return ResourceManager.GetString("Tag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 凭证检查||工资福利||招待||固资折旧||折旧测算||无形长摊||社保||社保明细工资人数||广宣||捐赠||利息||租金||补亏||其他事项||无限期结转扣除项目审核表||跨年度确认所得情况表||视同销售和房地产开发企业特定业务审核表||未按权责发生制确认收入审核表||投资收益审核表||专项用途财政性资金审核表||固定资产加速折旧审核表||资产损失税前扣除审核表||资产损失（专项申报）税前扣除审核表||企业重组审核表||政策性搬迁审核表||特殊行业准备金审核表||免税、减计收入及加计扣除优惠审核表||股息红利优惠审核表||综合利用资源生产产品取得的收入优惠审核表||金融保险等机构取得涉农利息保费收入优惠审核表||研发费用加计扣除优惠审核表||所得减免优惠审核表||抵扣应纳税所得额审核表||减免所得税优惠审核表||高新技术企业优惠情况审核表||软件、集成电路企业优惠情况审核表||税额抵免优惠审核表||境外所得税收抵免审核表||境外所得纳税调整后所得审核表||境外分支机构弥补亏损审核表||跨年度结转抵免境外所得税审核表||跨地区经营汇总纳税企业年度分摊企业所得税审核表||企业所得税汇总纳税分支机构所得税分配表 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Tag2 {
            get {
                return ResourceManager.GetString("Tag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主营收支||纳税申报数据||收入与申报核对表||毛利分析||制造费用、生产成本||成本倒轧||存货计价测试||主营税金||税费缴纳测算||税金申报明细||其他业务||营业费用||管理费用||财务费用||营外收支 的本地化字符串。
        /// </summary>
        public static string Tag3 {
            get {
                return ResourceManager.GetString("Tag3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本情况（封面）||1.保留意见||2.否定意见||3.无保留意见||4.无法表明意见||(二)企业基本情况和审核事项说明||(二)附表-科目说明||(二)附表-纳税调整额的审核||（三）企业所得税年度纳税申报表填报表单||A000000企业基础信息表||A100000中华人民共和国企业所得税年度纳税申报表（A类）||A101010一般企业收入明细表||A101020金融企业收入明细表||A102010一般企业成本支出明细表||A102020金融企业支出明细表||A103000事业单位、民间非营利组织收入、支出明细表||A104000期间费用明细表||A105000纳税调整项目明细表||A105010视同销售和房地产开发企业特定业务纳税调整明细表||A105020未按权责发生制确认收入纳税调整明细表||A105030投资收益纳税调整明细表||A105040专项用途财政性资金纳税调整表||A105050职工薪酬纳税调整明细表||A105060广告费和业务宣传费跨年度纳税调整明细表||A105070捐赠支出纳税调整明细表||A105080资产折旧、摊销情况及纳税调整明细表||A105081固定资产加速折旧、扣除明 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Tag4 {
            get {
                return ResourceManager.GetString("Tag4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货币资金||现金证明||银行调节||应收||预付||其他应收||存货||待摊预提||在建工程审核表||对外投资 的本地化字符串。
        /// </summary>
        public static string Tag5 {
            get {
                return ResourceManager.GetString("Tag5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应付||预收||其他应付||借款||实收公积||未分利润 的本地化字符串。
        /// </summary>
        public static string Tag6 {
            get {
                return ResourceManager.GetString("Tag6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 档案封面||待办事项||签发单||三级复核||业务约定||税审收费标准||当局声明||计划||内控||审核问卷||重大问题||交换意见||资料清单||审核标识||盘点表||通用记录||使用说明 的本地化字符串。
        /// </summary>
        public static string Tag81 {
            get {
                return ResourceManager.GetString("Tag81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本情况||资产负债表||利润表||余额表||检查表||凭证检查 的本地化字符串。
        /// </summary>
        public static string Tag82 {
            get {
                return ResourceManager.GetString("Tag82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货币资金||现金证明||银行调节||应收||预付||其他应收||存货||待摊预提||在建工程||对外投资||固资折旧||折旧测算||无形长摊 的本地化字符串。
        /// </summary>
        public static string Tag83 {
            get {
                return ResourceManager.GetString("Tag83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应付||预收||其他应付||借款||实收公积||未分利润 的本地化字符串。
        /// </summary>
        public static string Tag84 {
            get {
                return ResourceManager.GetString("Tag84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主营收支||其他业务||应交税费||收入与申报核对表||毛利分析||制造费用、生产成本||成本倒轧||存货计价测试||税金附加||税费缴纳测算||销售费用||管理费用||财务费用||营外收支||招待||工资福利||广宣||社保||社保明细工资人数||利息||租金 的本地化字符串。
        /// </summary>
        public static string Tag85 {
            get {
                return ResourceManager.GetString("Tag85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整事项||无限期结转扣除项目审核表||跨年度确认所得情况表||公允价值变动审定表||减值准备审核表||视同销售和房地产开发企业特定业务审核表||未按权责发生制确认收入审核表||投资收益审核表||专项用途财政性资金审核表||捐赠||固定资产加速折旧审核表||资产损失税前扣除审核表||企业重组审核表||政策性搬迁审核表||特殊行业准备金审核表||补亏||免税、减计收入及加计扣除优惠审核表||股息红利优惠审核表||研发费用加计扣除优惠审核表||所得减免优惠审核表||抵扣应纳税所得额审核表||减免所得税优惠审核表||高新技术企业优惠情况审核表||软件、集成电路企业优惠情况审核表||税额抵免优惠审核表||境外所得税收抵免审核表||境外所得纳税调整后所得审核表||境外分支机构弥补亏损审核表||跨年度结转抵免境外所得税审核表||跨地区经营汇总纳税企业年度分摊企业所得税审核表||企业所得税汇总纳税分支机构所得税分配表 的本地化字符串。
        /// </summary>
        public static string Tag86 {
            get {
                return ResourceManager.GetString("Tag86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报告正文||企业基本情况||封面||企业所得税年度纳税申报表填报表单||A000000 企业基础信息表||A100000 中华人民共和国企业所得税年度纳税申报表（A类）||A101010 一般企业收入明细表||A101020 金融企业收入明细表||A102010 一般企业成本支出明细表||A102020 金融企业支出明细表||A103000事业单位、民间非营利组织收入、支出明细表||A104000期间费用明细表||A105000纳税调整项目明细表||A105010视同销售和房地产开发企业特定业务纳税调整明细表||A105020未按权责发生制确认收入纳税调整明细表||A105030投资收益纳税调整明细表||A105040专项用途财政性资金纳税调整表||A105050职工薪酬支出及纳税调整明细表||A105060广告费和业务宣传费跨年度纳税调整明细表||A105070捐赠支出及纳税调整明细表||A105080 资产折旧、摊销及纳税调整明细表||A105090资产损失税前扣除及纳税调整明细表||A105100企业重组及递延纳税事项调整明细表||A105110政策性搬迁纳税调整明细表||A105120 特殊行业准备金 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Tag87 {
            get {
                return ResourceManager.GetString("Tag87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作底稿档案封面||业务档案索引||审核签发单||三级复核表||业务约定书||管理当局声明书||审核整体工作计划||内部控制制度调查问卷||审核调查问卷||重大问题请示报告||与客户交换意见记录||客户提供资料一览表||审核标识说明表||地税税务登记表||取数用基本情况表||资产负债表（小企业准则）||利润及利润分配表（小企业准则）||末级科目余额表||资产盘点明细表||工作底稿勾稽关系检查表||待办事项||工作底稿主页||通用工作记录表||收费计算表||使用说明 的本地化字符串。
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始凭证检查底稿||工资薪金、三项经费审核表||业务招待费审核表||固定资产及累计折旧审核表||固定资产折旧验算表（直线法）||无形资产、长期待摊费用审核表||各类社会保障性缴款和住房公积金审核表||社保明细和工资人数审核表||广告费、业务宣传费支出审核表||捐赠、赞助支出审核表||利息支出审核表||租金支出审核表||弥补亏损审核表||其他事项审核表||无限期结转扣除项目审核表||跨年度确认所得情况表||视同销售和房地产开发企业特定业务审核表||未按权责发生制确认收入审核表||投资收益审核表||专项用途财政性资金审核表||固定资产加速折旧、扣除审核表||资产损失税前扣除审核表||资产损失（专项申报）税前扣除审核表||企业重组审核表||政策性搬迁审核表||特殊行业准备金审核表||免税、减计收入及加计扣除优惠审核表||股息红利等权益性投资收益优惠审核表||综合利用资源生产产品取得的收入优惠审核表||金融、保险等机构取得涉农利息、保费收入优惠审核表||研发费用加计扣除优惠审核表||所得减免优惠审核表||抵扣应纳税所得额审核表||减免所得税优惠审核表||高新技术企业优惠情况审核表||软件、集成电路企业优惠情况审核表| [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主营业务收支审核表||纳税申报数据||收入与纳税申报核对审核表||主营业务毛利分析表||制造费用、生产成本审核表||主营业务成本倒轧审核表||存货计价测试表(加权平均)||主营业务及税金附加审核表||各税费缴纳情况审核表||地税网上申报明细查询结果||其他业务收支审核表||营业费用审核表||管理费用审核表||财务费用审核表||营业外收支审核表 的本地化字符串。
        /// </summary>
        public static string Text3 {
            get {
                return ResourceManager.GetString("Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本情况（封面）||1.保留意见||2.否定意见||3.无保留意见||4.无法表明意见||(二)企业基本情况和审核事项说明||(二)附表-科目说明||(二)附表-纳税调整额的审核||（三）企业所得税年度纳税申报表填报表单||A000000企业基础信息表||A100000中华人民共和国企业所得税年度纳税申报表（A类）||A101010一般企业收入明细表||A101020金融企业收入明细表||A102010一般企业成本支出明细表||A102020金融企业支出明细表||A103000事业单位、民间非营利组织收入、支出明细表||A104000期间费用明细表||A105000纳税调整项目明细表||A105010视同销售和房地产开发企业特定业务纳税调整明细表||A105020未按权责发生制确认收入纳税调整明细表||A105030投资收益纳税调整明细表||A105040专项用途财政性资金纳税调整表||A105050职工薪酬纳税调整明细表||A105060广告费和业务宣传费跨年度纳税调整明细表||A105070捐赠支出纳税调整明细表||A105080资产折旧、摊销情况及纳税调整明细表||A105081固定资产加速折旧、扣除明 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Text4 {
            get {
                return ResourceManager.GetString("Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货币资金审核表||现金证明书||银行存款余额调节表||应收账款审核表||预付账款审核表||其他应收款审核表||存货审核表||待摊费用、预提费用审核表||在建工程审核表||对外投资审核表 的本地化字符串。
        /// </summary>
        public static string Text5 {
            get {
                return ResourceManager.GetString("Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应付账款审核表||预收账款审核表||其他应付款审核表||借款审核表||实收资本、资本公积、盈余公积审核表||未分配利润审核表 的本地化字符串。
        /// </summary>
        public static string Text6 {
            get {
                return ResourceManager.GetString("Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap tree {
            get {
                object obj = ResourceManager.GetObject("tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Upload_to_the_Cloud_100px {
            get {
                object obj = ResourceManager.GetObject("Upload_to_the_Cloud_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon vpn_key {
            get {
                object obj = ResourceManager.GetObject("vpn_key", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 中汇LOGO {
            get {
                object obj = ResourceManager.GetObject("中汇LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 中汇标题 {
            get {
                object obj = ResourceManager.GetObject("中汇标题", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 地球 {
            get {
                object obj = ResourceManager.GetObject("地球", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 明正LOGO {
            get {
                object obj = ResourceManager.GetObject("明正LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
